[package]
name = "photo-kiosk"
version = "0.1.0"
edition = "2021"

# [profile.release]
# lto = "thin"
# strip = true

[dependencies]
glam = "0.29.2"
image = { version = "0.25.5", features = ["default-formats"], default-features = false }
miniquad = "0.4.7"
reqwest = { version = "0.12.12", default-features = false,  features = ["json", "blocking", "http2", "rustls-tls"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
