[package]
name = "photo-kiosk"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "thin"
strip = true

[dependencies]
bytes = "1.9.0"
env_logger = "0.11.6"
glam = "0.29.2"
glium = { version = "0.36.0", default-features = false, features = ["glutin_backend"] }
glutin = { version = "0.32.1", default-features = false, features = ["egl", "x11"] }
glutin-winit = { version = "0.5.0", default-features = false, features = ["egl", "x11"] }
image = { version = "0.25.5", features = ["default-formats"], default-features = false }
log = "0.4.22"
obj = "0.10.2"
raw-window-handle = "0.6.2"
reqwest = { version = "0.12.12", features = ["blocking", "charset", "json", "rustls-tls"], default-features = false }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
winit = { version = "0.30.8", default-features = false, features = ["x11"] }
