[target.arm-unknown-linux-gnueabihf]
# dockerfile = "./cross2.Dockerfile"
image = "localhost/cross-custom-syno-photo-frame:arm-unknown-linux-gnueabihf-9a20c"
[target.arm-unknown-linux-musleabihf]
dockerfile = "./cross.Dockerfile"
#pre-build = [
#    "dpkg --add-architecture $CROSS_DEB_ARCH",
#    "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH libssl-dev pkg-config libsdl2-dev:$CROSS_DEB_ARCH"
#]
